-- =====================================================================
-- Opportunity Hub — 18 sample opportunities
-- Run in Supabase > SQL Editor AFTER db/schema.sql.
-- Safe to re-run: rows already present (same title + organization) are skipped.
-- Deadlines are relative to today, so the listings never look stale.
-- Organizations are fictional; replace apply_url values with real links.
-- =====================================================================
with s(title, organization, description, type, category, location, work_mode, is_paid,
       salary_min, salary_max, currency, experience_level, skills, apply_url, days, featured) as (values
 ('Frontend Developer Intern','Northwind Labs','Build accessible UI components with React and TypeScript alongside a small product team. You will ship one real feature, get weekly code reviews and a named mentor.','internship','Engineering','Bengaluru, IN','hybrid',true,20000,30000,'INR','entry',array['React','TypeScript','CSS'],'https://example.com/apply/frontend-intern',6,true),
 ('Graduate Data Analyst','Meridian Analytics','Turn messy operational data into weekly insights for retail clients. SQL, dashboards and clear writing matter more than prior experience. Structured 6-month onboarding.','job','Data','Remote (India)','remote',true,500000,700000,'INR','entry',array['SQL','Excel','Power BI'],'https://example.com/apply/data-analyst',20,true),
 ('Women in STEM Merit Scholarship','Asha Foundation','Tuition support of up to INR 1,00,000 for second-year engineering and science students with a strong academic record and demonstrated financial need.','scholarship','Education','India','remote',false,null,null,'INR','entry',array['Academics'],'https://example.com/scholarship',35,false),
 ('Smart City Hackathon 2026','CivicTech India','48-hour build sprint on transport, waste and water problems. Teams of 2 to 4. Cash prizes and a pilot opportunity with two municipal bodies.','hackathon','Competitions','Patna, IN','onsite',false,null,null,'INR','entry',array['Python','IoT','Design'],'https://example.com/hackathon',12,true),
 ('Junior UX Designer','Lattice Studio','Run research, map flows and build prototypes for fintech clients. A portfolio of any real or student project is enough to apply.','job','Design','Hyderabad, IN','hybrid',true,400000,600000,'INR','entry',array['Figma','Research','Prototyping'],'https://example.com/apply/ux',15,false),
 ('Machine Learning Research Fellowship','Open Science Institute','Six-month stipend fellowship working with a faculty mentor on open datasets for Indian languages. Publication support included.','fellowship','Research','Remote (India)','remote',true,35000,35000,'INR','entry',array['Python','PyTorch','NLP'],'https://example.com/fellowship',28,true),
 ('Cloud Fundamentals Bootcamp','SkillBridge','Four-week evening bootcamp covering Linux, networking and a cloud certification path. Free for final-year students.','course','Learning','Online','remote',false,null,null,'INR','entry',array['Linux','AWS','Networking'],'https://example.com/bootcamp',9,false),
 ('Associate Product Manager','Kite Commerce','Own small slices of the buyer app: write specs, talk to users and work with engineers every day. Open to freshers with a project or club-leadership background.','job','Product','Gurugram, IN','onsite',true,900000,1200000,'INR','entry',array['Product','Analytics','Communication'],'https://example.com/apply/apm',3,false),
 ('Campus Career Fair: Tech & Startups','Opportunity Hub','Meet 40+ early-stage companies hiring interns and freshers. Bring your resume; on-the-spot interviews and a free resume clinic.','event','Networking','Kolkata, IN','onsite',false,null,null,'INR','entry',array['Networking','Interviewing'],'https://example.com/fair',18,false),
 ('Backend Engineer (New Grad)','Orbit Payments','Design and operate Go services that process millions of payments. Strong fundamentals in data structures and databases required.','job','Engineering','Bengaluru, IN','hybrid',true,1400000,1800000,'INR','entry',array['Go','PostgreSQL','APIs'],'https://example.com/apply/backend',25,true),
 ('Digital Marketing Intern','Brightleaf Media','Plan and run social campaigns for D2C brands, learn SEO basics and report weekly on what worked. Great for communication and business students.','internship','Marketing','Mumbai, IN','hybrid',true,12000,18000,'INR','entry',array['SEO','Social Media','Copywriting'],'https://example.com/apply/marketing-intern',10,false),
 ('Customer Success Associate','Helio Software','Onboard new SaaS customers, answer product questions and feed insights back to the product team. Training provided; clear English and empathy required.','job','Customer Success','Pune, IN','hybrid',true,350000,480000,'INR','entry',array['Communication','Problem Solving','CRM'],'https://example.com/apply/cs-associate',14,false),
 ('Open Source Summer Program','Commons Collective','Eight weeks contributing to a real open source project with a maintainer mentor. Monthly stipend for accepted contributors.','fellowship','Engineering','Remote','remote',true,25000,25000,'INR','entry',array['Git','JavaScript','Documentation'],'https://example.com/oss-summer',30,true),
 ('Junior Cybersecurity Analyst','Bastion Secure','Monitor alerts, triage incidents and help harden client systems in a 24x7 security operations team. Shift allowance and certification support.','job','Security','Noida, IN','onsite',true,500000,750000,'INR','entry',array['Networking','SIEM','Linux'],'https://example.com/apply/security-analyst',22,false),
 ('Financial Analyst Trainee','Crestwood Capital','Two-year rotational program across equity research, credit and operations. Strong Excel skills and curiosity about markets expected.','job','Finance','Mumbai, IN','onsite',true,600000,850000,'INR','entry',array['Excel','Finance','Valuation'],'https://example.com/apply/fin-trainee',17,false),
 ('Content Writer Intern','Paperplane Studio','Write blog posts, newsletters and case studies for tech clients. Editing feedback on every piece and a published portfolio by the end.','internship','Content','Remote (India)','remote',true,10000,15000,'INR','entry',array['Writing','Research','Editing'],'https://example.com/apply/writer-intern',8,false),
 ('National Innovation Challenge for Students','Bharat Startup Forum','Pitch a prototype to a panel of founders and investors. Winners receive seed grants of up to INR 5,00,000 and incubation space.','hackathon','Competitions','Online','remote',false,null,null,'INR','entry',array['Entrepreneurship','Prototyping','Pitching'],'https://example.com/innovation-challenge',40,true),
 ('Postgraduate Scholarship in Public Policy','Lokniti Trust','Full tuition and living stipend for a one-year public policy master''s. Open to graduates with 0-3 years of experience and a commitment to public service.','scholarship','Education','India','onsite',false,null,null,'INR','entry',array['Policy','Research','Writing'],'https://example.com/policy-scholarship',45,false)
)
insert into public.opportunities
  (title, organization, description, type, category, location, work_mode, is_paid,
   salary_min, salary_max, currency, experience_level, skills, apply_url, deadline, featured, status)
select s.title, s.organization, s.description, s.type::public.opportunity_type, s.category, s.location,
       s.work_mode::public.work_mode, s.is_paid, s.salary_min::numeric, s.salary_max::numeric, s.currency,
       s.experience_level, s.skills, s.apply_url, now() + make_interval(days => s.days), s.featured, 'published'
from s
where not exists (select 1 from public.opportunities o where o.title = s.title and o.organization = s.organization);
